version: '3.9'

services:
  app:
    container_name: school-system
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4040:4040"
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    networks:
      - my-network

  mongo:
    container_name: school-system-mongo
    image: mongo:latest
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - my-network

  nginx:
      container_name: school-system-nginx
      image: nginx:latest
      ports:
        - "8080:8080"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - app
      networks:
        - my-network

  angular:
    container_name: school-system-angular
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4500:4500"
    networks:
      - my-network

volumes:
  mongo_data: 

networks:
  my-network:
    driver: bridge