export enum URLSegment {
  Auth = 'auth/',
  User = 'user/',
  Director = 'director/',
  Domain = 'domain/',
  Lookups = 'lookups/',
  SuperAdmin = 'superAdmin/',
  Teacher = 'teacher/',
  Student = 'student/',
  classRoom = 'class-room/',
  parent = 'parent/',
  School = 'school/',
  Invoice = 'invoice/',
  Ticket  = 'ticket/',
  Group  = 'group/',
  Skill = 'skill/',
  Activity = 'activity/',
  Classes  = 'classes/',
  Event = 'event/',
  Payment = 'payment/',
}
